spring:
  application:
    name: 'Mantime'
  main:
    banner-mode: off
task:
  template:
    allowMultipleTasks: false
management:
  endpoints:
    web:
      base-path: '/status'
  metrics:
    enable:
      http: false