spring:
  config:
    import: file:.env.local[.properties]
  h2:
    console:
      enabled: true
      path: '/h2-console'
  datasource:
    url: 'jdbc:h2:file:./app-db'
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: '*'